### ISSUE TITLE
No bones displayed when trying to edit

### ISSUE THREAD

**Issue by frostbl00m** [Aether-Tools/CustomizePlus#19] opened 2024-07-13 00:46 UTC
When I open Customize+ and create a new template, no bones are displayed. When I go to older templates, the only bones that are displayed are the bones that were previously edited.
![Screenshot 2024-07-12 203557](https://github.com/user-attachments/assets/502a4e2c-6bd0-4a50-8e5a-0c4207744da2)
![Screenshot 2024-07-12 204554](https://github.com/user-attachments/assets/7232b0c7-f82d-47a3-904e-239200e30496)

**Comment by RisaDev** [comment] 2024-07-13 11:47
I have noticed that a lot of people been complaining about that. Will do some tests when I finish MSQ.

Right now it seems like the fix for this is to restart your game.

**Comment by frostbl00m** [comment] 2024-07-13 22:18
Just wanted to let you know, after restarting my game I still don't see any of the bones.

**Comment by Leinier12** [comment] 2024-08-09 20:58
Hello, i have the same problem listed above is there any fix or reason its happening? i tried restarting and still have the same issue.

**Comment by RisaDev** [comment] 2024-08-09 21:05
I don't have anything to add to this at this point, I have not been able to reproduce this so far.

**Comment by aetheiryte** [comment] 2024-08-20 22:56
I don't really have anything to add, only adding my voice to the "I am also having this issue" crowd. Only previously edited bones appear in the list on old templates, new templates have no bones at all. Restarting doesn't fix it. I actually don't know where to find the "reset plugin data and reload" function Enantiomorph mentioned to see if that fixes it for me.

**Comment by RisaDev** [comment] 2024-08-20 23:46
If you guys have nothing to add just don't comment. Those comments do nothing but add clutter.

**Comment by d87** [comment] 2024-09-11 09:33
I can that add I was able to fix it by toggling off Brio and Mare, but weirdly after i enabled them back C+ continued working from then on just fine, so i couldn't narrow it down further. Maybe the issue is related to plugin loading order then?
Also when this was happening it couldn't find any armature in the debug info

**Comment by RisaDev** [comment] 2024-10-20 23:52
This might be fixed in current testing build.

**Closed** 2024-10-26 17:27 UTC
Labels: bug, pending confirmation, no input needed, in testing
